version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:  
      - "38080:8080"
      - "38015:28015"
      - "39015:29015"
  web:
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - ./:/usr/src/
    working_dir: /usr/src/
    ports:
      - "33000:3000"
    depends_on:
      - db