version: '3'
services:
  db:
    image: rethinkdb:latest
    ports:  
      - "38080:8080"
      - "38015:28015"
      - "39015:29015"
  web:
    image: node:alpine
    volumes:
      - ./:/usr/src/
    working_dir: /usr/src/
    command: npm start
    ports:
      - "33000:3000"
    depends_on:
      - db